# Generated by Django 4.1.5 on 2023-04-09 14:14

from django.db import migrations, models
import ecom.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images', validators=[ecom.validators.validate_file_size]),
        ),
    ]
