# Generated by Django 4.1.5 on 2023-04-23 13:55

from django.db import migrations, models
import django.db.models.deletion
import ecom.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/images', validators=[ecom.validators.validate_file_size])),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecom.collection')),
            ],
        ),
    ]
